export enum Primitive {
	UUID = 'cds.UUID',
	Boolean = 'cds.Boolean',
	Integer = 'cds.Integer',
	Int16 = 'cds.Int16',
	Int32 = 'cds.Int32',
	Int64 = 'cds.Int64',
	UInt8 = 'cds.UInt8',
	Decimal = 'cds.Decimal',
	Double = 'cds.Double',
	Date = 'cds.Date',
	Time = 'cds.Time',
	DateTime = 'cds.DateTime',
	Timestamp = 'cds.Timestamp',
	String = 'cds.String',
	Binary = 'cds.Binary',
	LargeBinary = 'cds.LargeBinary',
	LargeString = 'cds.LargeString',
	Map = 'cds.Map',
	Vector = 'cds.Vector',
	Composition = 'cds.Composition',
	Association = 'cds.Association'
};