export enum Primitive {
	Guid = 'edm.Guid',
	Boolean = 'edm.Boolean',
	Byte = 'edm.Byte',
	Int16 = 'edm.Int16',
	Int32 = 'edm.Int32',
	Int64 = 'edm.Int64',
	Decimal = 'edm.Decimal',
	Double = 'edm.Double',
	Date = 'edm.Date',
	Time = 'edm.Time',
	DateTime = 'edm.DateTime',
	DateTimeOffset = 'edm.DateTimeOffset',
	Timestamp = 'edm.Timestamp',
	String = 'edm.String',
	Binary = 'edm.Binary',
};